### ISSUE TITLE
Commands on the Discord Side for on the fly configuration changes.

### ISSUE THREAD

**Issue by fortepc** [Bjornskjald/miscord#249] opened 2018-06-26 22:42 UTC
**Describe the solution you'd like**
I'd like to see miscord be able to have it's configuration editable from within discord. Ideally miscord would only listen for these commands in a specific channel, so that it doesn't have to worry about checking a user's permissions it would create it's own channel on joining a server `#miscord-admin` for example, and anyone who has access to that channel could change miscord's configuration. This channel should also be configurable, as some servers have a `#cmd` channel already for this reason and like to consolidate all the bots to the same channel.  

`@miscord#0000 set-channel [tagged channel, or numeric channel ID]`
This would move where miscord is listening for configuration commands.

`@miscord#0000 set-config messenger.username someusername@gmail.com`

`@miscord#0000 set-config messenger.password somepassword`

`@miscord#0000 set-config discord.renameChannels false`

`@miscord#0000 set-config messenger.ignoreEmbeds true`

`@miscord#00 set-config massMentions false`

`@miscord#0000 channel-link [Tagged Channel, or numeric channel ID] [Messenger group ID]`
This would add a new mapped channel to channels.yml 

**Describe alternatives you've considered**
Maybe at the very least a `@miscord reload-config` so that if I make changes to miscord's configuration I don't have to restart it. 

**Additional context**
`@miscord#0000` in the above example is just a placeholder, the bot should be able to know what it's own name is, and look for that, instead of expecting any hard coded username.

**Comment by Bjornskjald** [comment] 2018-06-26 22:44
it's actually a great idea, I was thinking about DMing a bot instead of a separate channels but I guess it's fine too

**Comment by fortepc** [comment] 2018-06-26 22:46
I personally like the dedicated seperate channel, as the servers are often managed by a team of people.

**Comment by Bjornskjald** [comment] 2018-06-27 20:01
I just realized this is a duplicate of #221, but I'll close the other issue because this is more detailed

**Closed** 2018-06-27 23:18 UTC
Labels: enhancement
