### ISSUE TITLE
for the bot in some it work 

### ISSUE THREAD

**Issue by RobCraftNet** [Bjornskjald/miscord#72] opened 2018-02-28 08:11 UTC
It like invite to my own server put on at so be can't put on other one post other server on discord when the in the server or not

**Comment by talormanda** [comment] 2018-02-28 13:24
I would like to help but your words do not form a readable sentence so I do not understand.

**Comment by Bjornskjald** [comment] 2018-02-28 16:54
Do you mean you can't put this bot on two servers at the same time?

**Comment by RobCraftNet** [comment] 2018-03-01 12:30
it send to other server to be like but this code is not send to other send

**Comment by RobCraftNet** [comment] 2018-03-01 12:32
yea @Bjornskjald

**Comment by Bjornskjald** [comment] 2018-03-01 17:08
@RobCraftNet it's because it is currently impossible, i'm gonna make it work in a couple of days.

**Comment by RobCraftNet** [comment] 2018-03-01 18:47
yea but like put the bot on a other and post on at othe server and sead the date for it on all other server

**Comment by Bjornskjald** [comment] 2018-03-08 18:46
Closed as a duplicate of #17

**Closed by Bjornskjald** 2018-03-08 18:46 UTC
Labels: enhancement
