### ISSUE TITLE
Error causing a cease in message relaying

### ISSUE THREAD

**Issue by ShinNinth** [Bjornskjald/miscord#174] opened 2018-04-06 11:57 UTC
_If you have a question, ask on the [Miscord Support server](https://discord.gg/DkmTvVz) instead_  
## Expected Behavior
Relaying messages

## Actual Behavior
Bot ceases to relay messages after the following error is produced in the console

ERR! getUserInfo { __ar: 1,
ERR! getUserInfo   error: 1357004,
ERR! getUserInfo   errorSummary: 'Sorry, something went wrong',
ERR! getUserInfo   errorDescription: 'Please try closing and re-opening your browser window.',
ERR! getUserInfo   payload: null,
ERR! getUserInfo   bootloadable: {},
ERR! getUserInfo   ixData: {},
ERR! getUserInfo   gkxData: {},
ERR! getUserInfo   lid: '6541285473297805330' }

As a note I have had this issue since i first encountered your application and have just been holding out hoping one of your enhancements would have taken care of it =/.

## Steps to Reproduce the Problem

  1. This error usually crops up after 2-3 days of the bot running on a dedicated machine
  2.  Error can be worked around by ctrl+break to exit the bot and then restarting the bot but will eventually crop back up again

## Specifications

  - Platform: windows
  - Version (`miscord -v`): 2.7.7
  - Node.js version (`node -v`): v8.11.0

**Comment by Bjornskjald** [comment] 2018-04-06 13:51
Duplicate of #168... still working on it

**Closed** 2018-04-06 20:35 UTC
